### ISSUE TITLE
Header 컴포넌트 레이아웃 그리기

### ISSUE THREAD

**Issue by Kim-DaHam** [Kim-DaHam/Portfolly#1]
## 개요
Header 컴포넌트 레이아웃을 간단하게 그립니다.

### ✅ Todo
- [x] `boder`, `backgroud-color` 로 영역을 표시한다.
- [x] 로고, 검색바, 버튼(로그인, 체험판 시작, 사용자 메뉴)으로 구성된다.
- [x] 스크롤을 내려도 브라우저 상단에 고정되도록 `position: fixed` 한다.
- [x] 검색바(SearchBar)는 Intro 화면에서는 보이지 않게 한다.(Intro 페이지 제외 모두 보임)
- [x] 검색바와 사용자 메뉴 버튼을 클릭하면 Popper(모달 비슷한 거)가 나타난다.
  - [x] Popper가 나타나면 모든 스크롤이 금지된다.
  - [x] Popper 바깥 영역을 클릭하면 다시 사라진다.
