### ISSUE TITLE
Main 페이지 레이아웃 그리기

### ISSUE THREAD

**Issue by Kim-DaHam** [Kim-DaHam/Portfolly#10]
## 개요
Main 페이지의 레이아웃 구조를 간단하게 그립니다.

### ✅ Todo
- [x] PortfolioItem을 Grid로(가로 최대 7개) 정렬한다. 
- [x] PortfolioItem 하단에 작성자 프로필, 작성자명, 프로젝트 제목이 있다.
- [x] 작성자 정보란에 마우스를 hover하면 북마크 버튼, 메뉴 버튼이 나타난다.
  - [x] 메뉴 버튼을 클릭하면 Popper가 나타난다.
  - [x] Popper에는 'Share, Download All' 버튼이 있다.
- [x] Filter 버튼을 누르면 SearchBarModal이 나타난다.
- [x] 포트폴리오 섹션 별 카테고리를 가로 슬라이더로 확인할 수 있다.
- [x] Header에 현재 포트폴리오 섹션을 표시한다.
  - [x] 더보기 아이콘을 클릭하면 다른 포트폴리오 섹션에 대한 Popper가 등장한다.

### 추가 사항
Download All 버튼은 다른 버튼으로 변경될 수 있습니다.
