### ISSUE TITLE
PortfolioDetail 페이지 레이아웃 그리기

### ISSUE THREAD

**Issue by Kim-DaHam** [Kim-DaHam/Portfolly#18]
## 개요
PortfolioDetail.tsx 페이지 레이아웃을 간단하게 그린다.

### ✅ Todo
- [x] Header가 존재한다.
- [x] 좌측에 포트폴리오 영역, 우측에 Aside(사용자 정보, 포트폴리오 정보 등)영역으로 나뉘어져 있다.
  - [x] 포트폴리오 영역: PortfolioEdit.tsx 페이지에서 작성한 게시물 내용이 들어간다.
  - [x] 사용자 정보: 사용자 프로필(Default), 문의하기 버튼
  - [x] 포트폴리오 정보: 카테고리, 제목, 좋아요, 북마크, 사용자 태그, 프로젝트 설명
  - [x] 이 전문가의 다른 포트폴리오
    - [x] 최대 9개 바둑판 모양으로 보여주고 '>' 버튼 클릭 시 사용자 페이지(포트폴리오 카테고리)로 이동한다.
- [x] 문의하기 버튼 클릭 시 기본적인 문의 폼 Modal이 오픈된다.
  - [x] 의뢰 제목, 의뢰 내용, 원하는 가격 견적, 요구 기간

### 추가 사항
우선순위에 따라 기능이 변동될 수 있습니다.
