### ISSUE TITLE
PortfolioDetail 페이지 기능 구현하기

### ISSUE THREAD

**Issue by Kim-DaHam** [Kim-DaHam/Portfolly#19]
## 개요
PortfolioDetail.tsx 페이지의 기능을 구현한다.

### ✅ Todo
- [x] 좋아요, 북마크 버튼 클릭 시 버튼 색상이 바뀌며 등록/취소 된다.
  - [x] 좋아요 버튼 옆에 좋아요 수가 있다.
- [x] '이 전문가의 다른 포트폴리오' 영역 아이템을 클릭하면 해당 PortfolioDetail 페이지로 이동한다.
- [x] 문의하기 버튼 클릭 시 채팅 페이지로 이동한다.

### 추가 사항
공유하기 버튼의 경우 클릭 시 그냥 url만 복사되게 할지, 다양한 애플리케이션 공유 옵션을 넣을지 고민 중에 있습니다.
