### ISSUE TITLE
Intro 페이지 레이아웃 그리기

### ISSUE THREAD

**Issue by Kim-DaHam** [Kim-DaHam/Portfolly#2]
## 개요
Intro 페이지 레이아웃을 간단하게 그립니다.

### ✅ Todo
- [x] 가장 먼저 홈페이지 소개가 화면 가득히 보이게 한다.
- [x] 스크롤이 브라우저 전체 화면 단위로 부드럽게 이동한다.
- [x] 홈페이지 소개 하단으로 포트폴리오 Preview 5가지(App, Web, Illustration, Graphics, Video)가 한 화면씩 나타난다.
- [x] Preview 마다 View More 버튼이 존재한다.
- [x] 간단한 소개 문구를 적는다.
- [x] Header 컴포넌트(레이아웃)을 넣는다.
- [x] Footer 컴포넌트(레이아웃)을 넣는다.
