### ISSUE TITLE
PortfolioEdit 페이지 레이아웃 그리기

### ISSUE THREAD

**Issue by Kim-DaHam** [Kim-DaHam/Portfolly#20]
## 개요
PortfolioEdit.tsx 페이지 레이아웃을 간단하게 그린다.

### ✅ Todo
- [x] 좌측에 에디터, 우측에 추가 정보 입력란이 존재한다.
  - [x] ReactQuill 에디터를 사용한다.
  - [x] 추가 정보: 제목, 카테고리, 사용자 태그, 포트폴리오 설명
- [x] 사용자 태그에 마우스 hover 시 x 아이콘 표시
  - [x] 사용자 태그 입력란에는 나타나지 않음
  - [x] 사용자 태그 입력란은 조금 더 진한 바탕 색, 흰 글씨
- [x] 카테고리 Selector, 섹션 Selector가 존재한다.
