### ISSUE TITLE
MyPage 페이지 레이아웃 그리기

### ISSUE THREAD

**Issue by Kim-DaHam** [Kim-DaHam/Portfolly#28]
## 개요
MyPage.tsx 페이지의 레이아웃을 그린다.

### ✅ Todo
- [x] 사용자 권한(전문가/의뢰인)에 따라 구성이 다르다.
- [x] 전문가 마이페이지는 다음 정보를 포함한다.
  - [x] 사용자 프로필/문의하기 버튼
  - [x] 소개/경력사항/총 경력/희망 급여/전문 분야 및 상세 분야/보유 기술
  - [x] 포트폴리오
  - [x] 받은 리뷰
  - [x] 활동 정보(총 작업 수/만족도/연락 가능 시간)
- [x] 전문가 전용 마이페이지(본인만 열람 가능)
  - [x] 판매 관리 카테고리
    - [x] 진행중/작업물 발송/취소, 문제 해결 건수를 확인 가능하다.
    - [x] 구매 확정, 작성 가능한 리뷰, 주문 취소 건수를 확인 가능하다.
    - [x] 판매 내역을 조회할 수 있다.
      - [x] 조회 필터: 판매 상태(진행중, 작업물 도착, 구매 확정, 주문 취소, 분쟁 조정), 기간, 닉네임or서비스명 검색어 입력
- [x] 의뢰인 마이페이지는 다음 정보를 포함한다.
  - [x] 사용자 프로필/소개/지역
  - [x] 받은 리뷰
  - [x] 활동 정보(총 의뢰 수/만족도)
- [x] 의뢰인 전용 마이페이지(본인만 열람 가능)
  - [x] 구매 관리 카테고리
    - [x] 진행중/작업물 발송/취소, 문제 해결 건수를 확인 가능하다.
    - [x] 구매 확정, 작성 가능한 리뷰, 주문 취소 건수를 확인 가능하다.
    - [x] 구매 내역을 조회할 수 있다.
      - [x] 조회 필터: 판매 상태(진행중, 작업물 도착, 구매 확정, 주문 취소, 분쟁 조정), 기간, 닉네임or서비스명 검색어 입력

### 추가 사항
우선 순위에 따라 변동할 수 있습니다.
