### ISSUE TITLE
PortfolioItem 컴포넌트 만들기

### ISSUE THREAD

**Issue by Kim-DaHam** [Kim-DaHam/Portfolly#3]
## 개요
Intro 페이지의 Preview 컴포넌트에 들어가는 PortfolioItem 컴포넌트를 만든다.

PortfolioItem은 개별 포트폴리오 컴포넌트로, 다음과 같이 사용된다.
* Main 페이지에서 Grid로 배치한 뒤 무한스크롤
* 클릭하면 포트폴리오 상세 페이지로 이동

### ✅ Todo
- [x] `border`, `background-color`로 간단한 레이아웃을 그린다.
- [x] 포트폴리오 5가지 섹션 별로 크기 비율이 다르게 그려지도록 한다.
- [x] 썸네일 캐러셀을 만든다.
  - [x] 마우스를 hover 했을 때만 나타난다.
  - [x] 캐러셀이 좌우 끝까지 도달하면 prev, next 버튼이 보이지 않는다.
- [x] 클릭 시 해당 포트폴리오 상세 페이지로 이동한다.
