### ISSUE TITLE
Intro 페이지 기능 구현하기

### ISSUE THREAD

**Issue by Kim-DaHam** [Kim-DaHam/Portfolly#4]
## 개요
Intro 페이지에 기능을 추가합니다.

### ✅ Todo
- [x] 서버에서 PortfolioItem을 불러온다.
  - [x] 최신 인기 포트폴리오 top3~1개만 가져온다.
- [x] ViewMore 버튼 클릭 시 해당 섹션의 Main 페이지로 이동한다.
