### ISSUE TITLE
MainPage 기능 구현하기

### ISSUE THREAD

**Issue by Kim-DaHam** [Kim-DaHam/Portfolly#45]
## 개요
MainPage.tsx 페이지 기능을 구현한다.

### ✅ Todo
- [x] Section마다 Title, Summary 바꾸기
  - [x] assets/phrase 하위에 섹션별 고정 문구 관리
- [x] CategorySlider 별도 컴포넌트로 분리하기
  - [x] Section 별 카테고리 보여주기
- [x] Section마다 PortfolioItem 다르게 보여주기
- [x] 모킹 서버로 더미 데이터 불러오기 테스트
  - [x] Android/iOS는 limit=30, 그 외 limit=20
- [x] 무한 스크롤
