### ISSUE TITLE
SearchBar 컴포넌트 만들기

### ISSUE THREAD

**Issue by Kim-DaHam** [Kim-DaHam/Portfolly#5]
## 개요
SearchBar 컴포넌트를 구현합니다.

### ✅ Todo
- [x] 현재 포트폴레오 섹션 내 작성자, 태그, 카테고리 검색이 가능하다.
- [x] 검색어 입력 시 해당하는 키워드 결과가 하단에 일렬로 나타난다.
  - [x] 가장 유사한 첫 번째 결과에 자동 focus 되어있다. (진한 회색 등으로 표시, 엔터 시 해당 페이지로 이동)
- [ ] ctrl+k 단축키를 누르면 검색창 Popper가 자동 오픈된다.
