### ISSUE TITLE
Header 컴포넌트 기능 구현하기

### ISSUE THREAD

**Issue by Kim-DaHam** [Kim-DaHam/Portfolly#6]
## 개요
Header 컴포넌트가 모든 동작을 수행하도록 기능을 추가합니다.

### ✅ Todo
- [x] 로고 버튼 클릭 시 Android/iOS 섹션의 Main 페이지로 이동한다.
- [x] Log in 버튼 클릭 시 LogIn 페이지로 이동한다.
- [x] Start Trial Version 버튼 클릭 시 체험판 시작 페이지로 이동한다.
- [x] Menu 버튼 컴포넌트
  - [x] 비로그인 시 일반 햄버거 메뉴 아이콘 모양
  - [x] 로그인 시 메뉴 아이콘 좌측에 사용자 프로필 생김
  - [x] 로그인/비로그인 Popper 내용이 다름
